# =========================
# DATABASE CONFIGURATION
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# =========================
# EMAIL CONFIGURATION
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# =========================
# JWT CONFIGURATION
# =========================
app.jwtExpirationMs=1000000000

# =========================
# ACTUATOR CONFIGURATION
# =========================
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always